// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKjAUM9NOXsV-I5SnrueBEukSIHHGXr_Y',
    appId: '1:397425488227:web:96063d355557d25adea356',
    messagingSenderId: '397425488227',
    projectId: 'lsbu-int-std-portal',
    authDomain: 'lsbu-int-std-portal.firebaseapp.com',
    storageBucket: 'lsbu-int-std-portal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGjsMSb-r_c3Cdu7bM2ao1emewempJueE',
    appId: '1:397425488227:android:5592c3c8bce3231bdea356',
    messagingSenderId: '397425488227',
    projectId: 'lsbu-int-std-portal',
    storageBucket: 'lsbu-int-std-portal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0SmfJYGjzdj_dFgGBxPl_yW_zjdrDBz4',
    appId: '1:397425488227:ios:b68eda1723d7d8e2dea356',
    messagingSenderId: '397425488227',
    projectId: 'lsbu-int-std-portal',
    storageBucket: 'lsbu-int-std-portal.appspot.com',
    iosClientId: '397425488227-lvl7tr5fk87e5cn8gtl3q7db3vsjclfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.lsbuPortalWebPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0SmfJYGjzdj_dFgGBxPl_yW_zjdrDBz4',
    appId: '1:397425488227:ios:b68eda1723d7d8e2dea356',
    messagingSenderId: '397425488227',
    projectId: 'lsbu-int-std-portal',
    storageBucket: 'lsbu-int-std-portal.appspot.com',
    iosClientId: '397425488227-lvl7tr5fk87e5cn8gtl3q7db3vsjclfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.lsbuPortalWebPortal',
  );
}
